# subject: the subject of the papers you want to collect
#subject: 'cat:cs.RO OR cat:cs.AI OR cat:cs.ML'
#subject_query: 'cat:cs.RO'
subject_query: cat:cs.*

keyword_query:
  key1:
    keywords:
      - "manipulation"
      - "LLM, VLM"
    weight: 2
  key2:
    keywords:
      - "RL"
      - "LLM"
      - "manipulation"
    weight: 6